# ... (resto do seu arquivo) ...

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- COMEÇO DAS NOVAS ETAPAS ---
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # MUDE ESTE NÚMERO SE SEU PROJETO USA OUTRA VERSÃO DO NODE.JS (ex: '20' ou '22')

      - name: Instalar dependências
        run: npm ci # Ou 'npm install' se você preferir, mas 'npm ci' é recomendado para CI/CD

      - name: Construir o projeto
        run: npm run build # ESTE É O COMANDO QUE CRIA A PASTA 'build'
      # --- FIM DAS NOVAS ETAPAS ---

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GIROFIPE }}'
          projectId: girofipe
          # ... (o resto das configurações do seu deploy) ...

# ... (fim do seu arquivo) ...
