name: firebase-hosting-merge.yml
on: # <--- Procure por esta linha 'on:'
  push:
    branches:
      - main # <--- Certifique-se de que isso esteja presente e correto

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Mude para a versão do Node.js que seu projeto usa

      - name: Instalar dependências
        run: npm ci

      - name: Construir o projeto
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GIROFIPE }}'
          projectId: girofipe
          channelId: live # <--- Adicione/descomente esta linha
          # expires: 7d # Você pode remover esta linha se estiver deployando para 'live'
          
